// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(WalkBooksDbContext))]
    [Migration("20260909015846_AddGenreMedium")]
    partial class AddGenreMedium
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.GraphQL.Types.BookCopyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LibraryTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LibraryTypeId");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("Api.GraphQL.Types.BookType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .HasColumnType("text");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Api.GraphQL.Types.GenreType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookTypeId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6f0b7b4-4f0b-4c3c-9c3b-4f6b9c3b4f01"),
                            Medium = "Book",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = new Guid("c1a9c2e3-7b4d-4c2f-8a1b-9d3e7f2a5b02"),
                            Medium = "Book",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = new Guid("d4e7f2a5-9c3b-4f6b-8a1b-7b4d3c2e6f03"),
                            Medium = "Book",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("e9f1a2b3-6c4d-4e5f-9a2b-8c3d4e5f6a04"),
                            Medium = "Book",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = new Guid("f2b3c4d5-7e6f-4a5b-8c9d-1e2f3a4b5c05"),
                            Medium = "Book",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("a3c4d5e6-8f7a-4b5c-9d0e-2f3a4b5c6d06"),
                            Medium = "Book",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = new Guid("b4d5e6f7-9a8b-4c5d-0e1f-3a4b5c6d7e07"),
                            Medium = "Book",
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = new Guid("c5e6f7a8-0b9c-4d5e-1f2a-4b5c6d7e8f08"),
                            Medium = "Book",
                            Name = "Literary Fiction"
                        },
                        new
                        {
                            Id = new Guid("d6f7a8b9-1c0d-4e5f-2a3b-5c6d7e8f9a09"),
                            Medium = "Book",
                            Name = "Young Adult"
                        },
                        new
                        {
                            Id = new Guid("e7a8b9c0-2d1e-4f5a-3b4c-6d7e8f9a0b10"),
                            Medium = "Book",
                            Name = "Children’s"
                        },
                        new
                        {
                            Id = new Guid("f8b9c0d1-3e2f-405b-4c5d-7e8f9a0b1c11"),
                            Medium = "Book",
                            Name = "Nonfiction"
                        },
                        new
                        {
                            Id = new Guid("a9c0d1e2-4f3a-416c-5d6e-8f9a0b1c2d12"),
                            Medium = "Book",
                            Name = "Biography"
                        },
                        new
                        {
                            Id = new Guid("b0d1e2f3-5a4b-427d-6e7f-9a0b1c2d3e13"),
                            Medium = "Book",
                            Name = "Memoir"
                        },
                        new
                        {
                            Id = new Guid("c1e2f3a4-6b5c-438e-7f80-0b1c2d3e4f14"),
                            Medium = "Book",
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = new Guid("d2f3a4b5-7c6d-449f-8011-1c2d3e4f5a15"),
                            Medium = "Book",
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = new Guid("e3a4b5c6-8d7e-45a0-9122-2d3e4f5a6b16"),
                            Medium = "Book",
                            Name = "Religion"
                        },
                        new
                        {
                            Id = new Guid("f4b5c6d7-9e8f-46b1-0233-3e4f5a6b7c17"),
                            Medium = "Book",
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = new Guid("a5c6d7e8-0f9a-47c2-1344-4f5a6b7c8d18"),
                            Medium = "Book",
                            Name = "Comics"
                        },
                        new
                        {
                            Id = new Guid("b6d7e8f9-10ab-48d3-2455-5a6b7c8d9e19"),
                            Medium = "Book",
                            Name = "Graphic Novels"
                        },
                        new
                        {
                            Id = new Guid("c7e8f9a0-21bc-49e4-3566-6b7c8d9e0f20"),
                            Medium = "Book",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("d8f9a0b1-32cd-40f5-4677-7c8d9e0f1a21"),
                            Medium = "Book",
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = new Guid("e9a0b1c2-43de-41a6-5788-8d9e0f1a2b22"),
                            Medium = "Book",
                            Name = "Art"
                        },
                        new
                        {
                            Id = new Guid("f0b1c2d3-54ef-42b7-6899-9e0f1a2b3c23"),
                            Medium = "Book",
                            Name = "Photography"
                        },
                        new
                        {
                            Id = new Guid("a1c2d3e4-65f0-43c8-79aa-0f1a2b3c4d24"),
                            Medium = "Book",
                            Name = "Reference"
                        },
                        new
                        {
                            Id = new Guid("b2d3e4f5-7601-44d9-8abb-1a2b3c4d5e25"),
                            Medium = "Book",
                            Name = "Education"
                        });
                });

            modelBuilder.Entity("Api.GraphQL.Types.LibrarySnapshotType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableBooks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LibraryTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RemovedBooks")
                        .HasColumnType("integer");

                    b.Property<string>("TakenByUser")
                        .HasColumnType("text");

                    b.Property<int>("TotalBooks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryTypeId");

                    b.ToTable("LibrarySnapshots");
                });

            modelBuilder.Entity("Api.GraphQL.Types.LibraryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Api.GraphQL.Types.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.GraphQL.Types.BookCopyType", b =>
                {
                    b.HasOne("Api.GraphQL.Types.BookType", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.GraphQL.Types.LibraryType", null)
                        .WithMany("Books")
                        .HasForeignKey("LibraryTypeId");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Api.GraphQL.Types.GenreType", b =>
                {
                    b.HasOne("Api.GraphQL.Types.BookType", null)
                        .WithMany("Genres")
                        .HasForeignKey("BookTypeId");
                });

            modelBuilder.Entity("Api.GraphQL.Types.LibrarySnapshotType", b =>
                {
                    b.HasOne("Api.GraphQL.Types.LibraryType", null)
                        .WithMany("LibrarySnapshots")
                        .HasForeignKey("LibraryTypeId");
                });

            modelBuilder.Entity("Api.GraphQL.Types.BookType", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Api.GraphQL.Types.LibraryType", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("LibrarySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
