// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(WalkBooksDbContext))]
    [Migration("20260907161941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.GraphQL.Types.BookCopyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LibraryTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LibraryTypeId");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("Api.GraphQL.Types.BookType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .HasColumnType("text");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Api.GraphQL.Types.GenreType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookTypeId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Api.GraphQL.Types.LibrarySnapshotType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableBooks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LibraryTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RemovedBooks")
                        .HasColumnType("integer");

                    b.Property<string>("TakenByUser")
                        .HasColumnType("text");

                    b.Property<int>("TotalBooks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryTypeId");

                    b.ToTable("LibrarySnapshots");
                });

            modelBuilder.Entity("Api.GraphQL.Types.LibraryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Api.GraphQL.Types.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.GraphQL.Types.BookCopyType", b =>
                {
                    b.HasOne("Api.GraphQL.Types.BookType", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.GraphQL.Types.LibraryType", null)
                        .WithMany("Books")
                        .HasForeignKey("LibraryTypeId");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Api.GraphQL.Types.GenreType", b =>
                {
                    b.HasOne("Api.GraphQL.Types.BookType", null)
                        .WithMany("Genres")
                        .HasForeignKey("BookTypeId");
                });

            modelBuilder.Entity("Api.GraphQL.Types.LibrarySnapshotType", b =>
                {
                    b.HasOne("Api.GraphQL.Types.LibraryType", null)
                        .WithMany("LibrarySnapshots")
                        .HasForeignKey("LibraryTypeId");
                });

            modelBuilder.Entity("Api.GraphQL.Types.BookType", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Api.GraphQL.Types.LibraryType", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("LibrarySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
